[tool.pyright]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "capstoneenv",
    ".agent",
    "artifacts",
    "data",
    ".git"
]

[tool.isort]
profile = "black"
skip = [
    "capstoneenv",
    ".agent",
    "artifacts"
]

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | capstoneenv
  | \.agent
  | artifacts
)/
'''
